codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  # Generated code
  - "**/zz_generated*.go"
  - "**/generated.pb.go"
  - "**/generated.proto"
  - "**/mock_*.go"
  - "**/fake_*.go"
  - "**/testdata/**"
  - "**/api/v1alpha1/*_types.go"  # API types are generated
  - "**/vendor/**"
  - "**/third_party/**"
  # Test helpers and test files
  - "**/*_test.go"
  - "**/test/**"
  - "**/test-bdd/**"
  # Low value code directories
  - "controllers/common/log/**"  # Log helpers
  - "cmd/**"  # Command entry points 
  - "pkg/log/**"  # Log utilities
  - "hack/**"  # Scripts and utilities
  - "config/**"  # Configuration
  - "docs/**"  # Documentation
