# permissions for end users to view rollingupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollingupgrade-viewer-role
rules:
- apiGroups:
  - upgrademgr.keikoproj.io
  resources:
  - rollingupgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - upgrademgr.keikoproj.io
  resources:
  - rollingupgrades/status
  verbs:
  - get
