apiVersion: v1
kind: ServiceAccount
metadata:
  name: rolling-upgrade-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolling-upgrade-sa-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rolling-upgrade-sa
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rolling-upgrade-controller
  name: rolling-upgrade-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolling-upgrade-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rolling-upgrade-controller
    spec:
      containers:
      - image: keikoproj/rolling-upgrade-controller:latest
        imagePullPolicy: Always
        name: rolling-upgrade-controller
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/role: master
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rolling-upgrade-sa
      serviceAccountName: rolling-upgrade-sa
      terminationGracePeriodSeconds: 30
