apiVersion: upgrademgr.keikoproj.io/v1alpha1
kind: RollingUpgrade
metadata:
  name: test-rollup
  namespace: upgrade-manager-system
spec:
  asgName: upgrademgr-eks-nightly-ASG
  nodeIntervalSeconds: 300
  postDrainDelaySeconds: 90
  postDrain:
    script: |
      echo "Hello, postDrain!"
    postWaitScript: |
      echo "Hello, postDrainWait!"
  postTerminate:
    script: |
      echo "Hello, postTerminate!"
  strategy:
    mode: eager
    drainTimeout: 600
    type: randomUpdate
    maxUnavailable: 1